POST http://localhost:5000/newstudentdetails
Content-Type: application/json

{
    "name": "what",
    "guardianName": "is",
    "phoneNumber": 12345,
    "email": "email",
    "address": "i",
    "interest": "live",
    "goals": "in",
    "source": "america",
    "courseInterested": false,
    "parentSupport": false,
    "onlineComfortable": false,
    "approvalStatus": true
}

###

POST http://localhost:5000/newclientdetails
Content-Type: application/json

{
    "representativeName": "please",
    "companyName": "bozo",
    "phoneNumber": 18090,
    "email": "abc@xyz.com",
    "address": "bozo",
    "requirement": "none",
    "deadline": "null",
    "budget": "28000",
    "source": "yahoo"
}

###
GET http://localhost:5000/getclientdata

###
GET http://localhost:5000/getstudentdata

###

GET http://localhost:5000/getcounts

###

GET http://localhost:5000/getunapprovedclients

###

GET http://localhost:5000/getunapprovedstudents